### PR TITLE
Created recommended button

### PR DESCRIPTION
**Pull request by OkechukwuNnujiJohn**
## Description

I created the functionality for the recommended button
The website will allow users to be able to upload images of their own clothes for sale

## Milestones
This pull requests is aimed towards providing the users with possible clothes/items that they might be interested in based on they favorite colors and favorite brands and their gender

## Resources
https://react.school/ui/button

## Test Plan
Screenshot 2023-07-13 at 8 56 18 PM
Screenshot 2023-07-13 at 8 56 31 PM
Screenshot 2023-07-13 at 8 56 51 PM

### CODE REVIEW

**Comment by OkechukwuNnujiJohn** [comment]
In the Upload-button commit I created an upload button for when the user wants to upload an item. 

This pull request is just uploading an item and updating the items database.
In the future I want to be able to tell which user uploaded with item

##resources: i met with a fellow intern who guided me on how she performed her own upload image feature

##Test Plan
https://www.loom.com/share/cf1a455875294f6e9b2249147fa5486b?sid=b27981ac-156c-4e01-96ed-db6250b37472

**Comment by JinyueHu** [comment]
Is it necessary for us to commit all `bluebird` files? Could you add summary on why do we integrate the whole library into your project?

**Comment by OkechukwuNnujiJohn** [comment]
In truth I don’t know whether the whole library is useful or not but I’d
rather not risk it. At the beginning of the project they made us start with
certain libraries so I guess it’s all just libraries that come together to
make the website run. And I feel like since it got updated without me
physically changing it then it is definitely working towards the code. I
mean we could later on look to see if we need everything.

Okechukwu.

**Comment by JinyueHu** [comment]
After syncing offline, we added new .gitignore files for node_module. 

The reason for this PR is big is we track all of the node_module files, hopefully we won't see the big commit int the next one.

BTW the demo looks great!

**Pull request merged**
